Modify docstrings
VIDA-NYU/tile2net pull request #45
Opened 2023-12-13 19:29 UTC by kmorhun

This Pull Request:
- Makes minor changes to the main `README.md` to clarify how to create a conda environment on first installing the program.
- Updates docstrings in `grid.py`, `pednet.py`, `raster.py`, `tile.py` to be more consistently formatted, and prepare them for future sphinx and ReadTheDocs documentation

2023-12-13 22:08 UTC, dhodcz2 commented on src/tile2net/raster/pednet.py
> +        list[shapely.geometry.LineString]
Returns
--------

2023-12-14 00:19 UTC, dhodcz2 requested changes
Have you been using GitHub CoPilot or another sort of LLM autocomplete? It would greatly accelerate this task if you have not already been using such a thing. [GitHub CoPilot is free for students.](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/github-global-campus-for-students/apply-to-github-global-campus-as-a-student)

2023-12-14 00:19 UTC, dhodcz2 commented on src/tile2net/raster/tile.py
> +        Returns (:class:`GeoDataFrame`): A :class:`GeoDataFrame` of a single tile
```suggestion
        Returns
        -------
        :class:`GeoDataFrame`
            A GeoDataFrame of a single tile.

```

2023-12-14 00:19 UTC, dhodcz2 commented on src/tile2net/raster/tile.py
> +        :class:`GeoDataFrame` | int
```suggestion
        :class:`GeoDataFrame` or int
```
numpy docstring style uses "or" instead or "|":
```    Returns
    -------
    out : ndarray or scalar
        Output array, element-wise comparison of `x1` and `x2`.
        Typically of type bool, unless ``dtype=object`` is passed.
        This is a scalar if both `x1` and `x2` are scalars.
```

2023-12-14 00:19 UTC, dhodcz2 commented on src/tile2net/raster/tile.py
>          ---------
```suggestion
        ----------
```

2023-12-17 21:50 UTC, dhodcz2 approved these changes
Looks great! Thank you for your time.

2023-12-17 22:25 UTC, Mary-h86 commented
Approved, thank you both @kmorhun and @dhodcz2 for the through and prompt exchange.

2023-12-17 22:28 UTC, merged